{% set name = "awkward" %}
{% set version = "1.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: 303bc0919f0932db3e78a9254c17fcdeb125e4be65cd894b40dfbc3bfddfc054

build:
  number: 0
  script:
    # Travis ppc64le doesn't have enough memory to build in more than one thread.
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}                  # [unix and (not (linux and ppc64le))]
    - export CMAKE_BUILD_PARALLEL_LEVEL=1                             # [linux and ppc64le]
    - export CMAKE_ARGS="$CMAKE_ARGS -DAWKWARD_EXTERNAL_PYBIND11=ON"  # [unix]
    - set CMAKE_BUILD_PARALLEL_LEVEL=%CPU_COUNT%                      # [win]
    - set CMAKE_ARGS="%CMAKE_ARGS% -DAWKWARD_EXTERNAL_PYBIND11=ON"    # [win]
    - python -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pyyaml                                 # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - pip
    - pybind11
    - python
    - pyyaml
    - setuptools <62
  run:
    - numpy >=1.13.1
    - python
    - packaging
    - importlib_resources  # [py<39]

test:
  imports:
    - awkward
    - awkward._connect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward-1.0
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
