{% set name = "awkward" %}
{% set version = "2.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: 481a1640760aa174cd34bf60d45920f70cfe8b555403962c4e5864929b0548e8

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >1.10.0
    - hatch-fancy-pypi-readme
  run:
    - python >=3.8
    - awkward-cpp ==32
    - importlib_metadata
    - numpy >=1.18.0
    - packaging
    - typing_extensions
    - fsspec >=2022.11.0

test:
  imports:
    - awkward
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scikit-hep/awkward
  doc_url: https://awkward-array.org/doc/main/

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
    - conda-forge/scikit-hep
    - ioanaif
