{% set name = "awkward" %}
{% set version = "2.6.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: 510779dc8f87f2b4147676c83fe52a2b3f68d0f0d319f7606ecbd01a65c57233

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >1.10.0
    - hatch-fancy-pypi-readme
  run:
    - python >=3.8
    - awkward-cpp ==35
    - importlib_metadata >=4.13.0
    - numpy >=1.18.0
    - packaging
    - typing_extensions >=4.1.0
    - fsspec >=2022.11.0

test:
  imports:
    - awkward
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scikit-hep/awkward
  doc_url: https://awkward-array.org/doc/main/

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
    - conda-forge/scikit-hep
    - ioanaif
