{% set name = "awkward" %}
{% set version = "2.6.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: 3e8397e9bc4902c02d521d19552a6afb2bd94406c767bc85894bdb4ab3e9c4dc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >1.10.0
    - hatch-fancy-pypi-readme
  run:
    - python >={{ python_min }}
    - awkward-cpp ==40
    - importlib-metadata >=4.13.0
    - numpy >=1.18.0
    - packaging
    - typing_extensions >=4.1.0
    - fsspec >=2022.11.0

test:
  imports:
    - awkward
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/awkward
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scikit-hep/awkward
  doc_url: https://awkward-array.org/doc/main/

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
    - conda-forge/scikit-hep
    - ioanaif
