{% set name = "awkward" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: c0357c62223fefcfc7a7565389dbd4db900623bf10eccf2bc8e87586ec59b38d

build:
  number: 1
  script:
    # Travis ppc64le doesn't have enough memory to build in more than one thread.
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}  # [not (linux and ppc64le)]
    - export CMAKE_BUILD_PARALLEL_LEVEL=1             # [linux and ppc64le]
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
  host:
    - pip
    - python
    - pyyaml
  run:
    - numpy >=1.13.1
    - python
    - setuptools

test:
  imports:
    - awkward
    - awkward._connect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward-1.0
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
