{% set name = "awkward" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: 66dcb1f5d26de22b742fcf6089f0dd5514527966acd7cab0922b57732fd72e44

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >1.10.0
    - hatch-fancy-pypi-readme
  run:
    - python >=3.7
    - awkward-cpp ==17
    - importlib_resources
    - numpy >=1.17.0
    - packaging
    - typing_extensions

test:
  imports:
    - awkward
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward-1.0
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
    - conda-forge/scikit-hep
    - ioanaif
