{% set name = "awkward" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: 3782b34643083d6ee7644e9fdb3daeafc4b6030a667f219fd61cb7b234976b68

build:
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
    - hatch-fancy-pypi-readme
  run:
    - numpy >=1.14.5
    - awkward_cpp ==2
    - python >=3.7
    - packaging
    - importlib_resources
    - typing_extensions >=4.1.0

test:
  imports:
    - awkward
    - awkward._connect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward-1.0
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
