{% set name = "awkward" %}
{% set version = "2.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awkward-{{ version }}.tar.gz
  sha256: 2a07bb0409411782fea226de5c817eb6e48db06d64323977581e4f304f911029

build:
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >1.10.0
    - hatch-fancy-pypi-readme
  run:
    - python >=3.7
    - awkward_cpp ==6
    - importlib_resources
    - numpy >=1.14.5
    - packaging
    - typing_extensions

test:
  imports:
    - awkward
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/awkward-1.0
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
