schema_version: 1

context:
  name: awkward
  version: "2.8.5"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/awkward-${{ version }}.tar.gz
  sha256: 4b9049440bb98214e05908098afd0d4f66af0b1b23c158159f9774db27447c89

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling >1.10.0
    - hatch-fancy-pypi-readme
  run:
    - python >=${{ python_min }}
    - awkward-cpp ==46
    - importlib-metadata >=4.13.0
    - numpy >=1.18.0
    - packaging
    - typing_extensions >=4.1.0
    - fsspec >=2022.11.0

tests:
  - python:
      imports:
        - awkward
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Manipulate JSON-like data with NumPy-like idioms.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/scikit-hep/awkward
  repository: https://github.com/scikit-hep/awkward
  documentation: https://awkward-array.org/doc/main/

extra:
  recipe-maintainers:
    - lgray
    - chrisburr
    - jpivarski
    - henryiii
    - agoose77
    - conda-forge/scikit-hep
    - ioanaif
    - ianna
